### ISSUE TITLE
Link to the H3.6M dataset on Readme is not working

### ISSUE THREAD

**Issue by edmondslho** [cotton-ahn/diffusion-motion-prediction#1]
Hi! The link for downloading the H3.6M zip file is no longer working. Would you mind sharing a new link or explaining how the dataset has to be downloaded?

**Comment by cotton-ahn** [comment]
Hi! I saw that the external link original from Stanford has been shut down. I think you need to download the original dataset from http://vision.imar.ro/human3.6m/description.php.
